# Generated by Django 3.0.8 on 2020-07-06 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=200)),
                ('date_endereco', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
